pipeline: Hard Negative Descriptors
data_params:
  work_dir: /data2/projects/HNDesc
  img_dir: /ssd/data/r2d2_data/aachen/images_upright/db
  st_dir: null
  hn_type: pair
  flow_dir: /ssd/data/r2d2_data/aachen/optical_flow
  kpts_descs_dir: /data2/pre_computed/Aachen-features/kpts/superpoint/db
  crop_size: 192
model_params:
  backbone_net: r2d2
  resume_snapshot: null #${output_params.snapshot_dir}/snapshot030000.pth
train_params:
  bs: 7
  lr: 1e-3
  n_workers: 8
  n_train_iters: 42700  # 4270 is the number of pairs. Let us train 70 epochs
  scheduler:
    lrate_decay_steps: 8000
    lrate_decay_factor: 0.5
output_params:
  out_dir: /data2/output/hndesc
  logger_dir: ${output_params.out_dir}/tboard/${model_params.backbone_net}_hn_{data_params.hn_type}_aachen_flow_TL
  snapshot_dir: ${output_params.out_dir}/snapshots/${model_params.backbone_net}_hn_{data_params.hn_type}_aachen_flow_TL
  validate_interval: 600 #600  # let us evaluate every epoch
  log_scalar_interval: 200 # 200
seed: 1984
hydra:
  run:
    dir: ${output_params.out_dir}
