pipeline: HNDesc
data_params:
  dataset_dir: /ssd/data/hndesc_train_data
  img_dir: ${data_params.dataset_dir}/MegaDepth
  st_dir: ${data_params.dataset_dir}/MegaDepth-stylized
  kpts_descs_dir: ${data_params.dataset_dir}/MegaDepth-light-features/kpts/superpoint
  global_desc_dict_train: null
  global_desc_dict_test: null
  crop_size: 256
  win_size: 3
model_params:
  backbone_net: caps
  resume_snapshot: null
train_params:
  bs: 16
  lr: 1e-4
  n_workers: 8
  n_train_iters: 220000
  scheduler:
    lrate_decay_steps: 50000
    lrate_decay_factor: 0.5
output_params:
  project_dir: .
  out_dir: ${output_params.project_dir}/output_hndesc/train/hndesc
  logger_dir: ${output_params.out_dir}/tboard/${model_params.backbone_net}_hn_minibatch_M_st__origval
  snapshot_dir: ${output_params.out_dir}/snapshots/${model_params.backbone_net}_hn_minibatch_M_st__origval
  validate_interval: 6000
  log_scalar_interval: 200
seed: 1984
