pipeline: Hard Negative Descriptors
data_params:
  work_dir: /data/projects/HNDesc
  img_dir: /ssd/data/CAPS-MegaDepth-release-light
  st_dir: /ssd/data/CAPS-MegaDepth-release-light/stylization_full
  precomputed_dir: /ssd/pre_computed/MegaDepth-light-features
  global_desc_dict_train: ${data_params.img_dir}/knn_caps_train_radenovic.pkl
  global_desc_dict_test: ${data_params.img_dir}/knn_caps_test_radenovic.pkl
  kpts_descs_dir: ${data_params.precomputed_dir}/kpts/superpoint
  crop_size: 256
  win_size: 3
model_params:
  backbone_net: caps
  resume_snapshot: null #${output_params.snapshot_dir}/snapshot030000.pth
train_params:
  bs: 16 #7
  lr: 1e-4 #1e-3
  n_workers: 8
  n_train_iters: 220000
  scheduler:
    lrate_decay_steps: 50000 #20000
    lrate_decay_factor: 0.5
output_params:
  out_dir: /data2/output/hndesc
  logger_dir: ${output_params.out_dir}/tboard/${model_params.backbone_net}_hn_minibatch_M_st__origval
  snapshot_dir: ${output_params.out_dir}/snapshots/${model_params.backbone_net}_hn_minibatch_M_st__origval
  validate_interval: 6000 #5000
  log_scalar_interval: 200
seed: 1984
hydra:
  run:
    dir: ${output_params.out_dir}
